### PR TITLE
Add nefcon installation way

### PR DESCRIPTION
**Pull request by nomi-san**
Ref #81

### CODE REVIEW

**Comment by nomi-san** [comment]
recheck

**Comment by MolotovCherry** [comment]
@nomi-san The bot should pass the check if you comment "I have read the CLA Document and I hereby sign the CLA"

(I can accept the PR after)

**Comment by nomi-san** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by nomi-san** [comment]
Thanks, I have signed the fork after this PR.

**Pull request merged**
